name: Issue Template
description: Use this template for creating new issues
title: "[ISSUE] - "
labels: ["bug", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please provide a clear and concise description of the issue.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Describe the expected behavior here.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: Describe the actual behavior here.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: [e.g. Windows, MacOS, Linux]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 22]