name: Kestra validate

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Consider using a stable version

      - name: Run a One-Line Script
        run: echo "Hello, world!"

      - name: Validate
        uses: kestra-io/validate-action@master  # Use a stable version if available
        with:
          directory: ./kestra/flow
          resource: flow
          server: http://127.0.0.1:8080
          
      - name: Run a Multi-Line Script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build completes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Deploy
        uses: kestra-io/deploy-action@master  # Use a stable version if available
        with:
          namespace: company.team  # Ensure this is correctly set for your organization/team
          directory: ./kestra/flow
          resource: flow
          server: http://127.0.0.1:8080
